// <auto-generated />
using DataverseMVCProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataverseMVCProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221128035659_SeedDatabase")]
    partial class SeedDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataverseMVCProject.Models.Customer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "4083 Bluff Street",
                            ContactPhone = "+306948521396",
                            Email = "HamedJeihlan@gmail.com",
                            Firstname = "Hamed",
                            Surname = "Jeihlan"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1079 West Street",
                            ContactPhone = "+306948521391",
                            Email = "LongLien@gmail.com",
                            Firstname = "Long",
                            Surname = "Lien"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1180 West Fork Drive",
                            ContactPhone = "+306948321396",
                            Email = "HamedJeihlan@gmail.com",
                            Firstname = "Hamed",
                            Surname = "Jeihlan"
                        },
                        new
                        {
                            Id = 4,
                            Address = "3841 Agriculture Lane",
                            ContactPhone = "+306948621396",
                            Email = "AdrinDatsk@gmail.com",
                            Firstname = "Adrin",
                            Surname = "Datsk"
                        },
                        new
                        {
                            Id = 5,
                            Address = "288 Ridenour Street",
                            ContactPhone = "+306948521296",
                            Email = "DostilOnzurnes@gmail.com",
                            Firstname = "Dostil",
                            Surname = "Onzurnes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
